#targets: prerequisites
	#command
	#command
	#etc.
# targets are file names, separated by spaces.
# commands are usually used to make the targets. Start with tabs. Not spaces
# prerequisites - file names separated by spaces. Exist before commands. Also called "dependencies".

hello:
	echo "herero"
	echo "This line will print if the the file hello does not exist"
# hello is the target.
# two echo commands
# no prerequisites/dependencies.
