#ifndef TEXCOORDS_H
#define TEXCOORDS_H

#include <vector>
#include <glm/glm.hpp>

// =============================================================================
// Texture coordinate generation
// =============================================================================
// The parameterisations, split out of Sphere.cpp and Cube.cpp so the student's
// work is one translation unit. TextureCache.cpp (decoding, GL upload, dedup)
// and Shape::uploadTexCoords() (the second VBO) stay given: image decoding and
// buffer plumbing are not the lesson. Deciding where a point on a surface
// lands in an image is.
//
// Texture::sample lives in TexCoords.cpp too, for the same reason -- bilinear
// filtering and wrapping are part of "how a texture is read", not part of
// "how a file is decoded".
//
// See SOLUTION-LIBRARIES.md and ASSIGNMENTS.md.

namespace TexCoords {

// Spherical mapping, one UV per unique vertex, in the same order
// Sphere::setupSphere() emits them: the outer loop runs y over latitude
// (0..latSegments inclusive) and the inner loop x over longitude.
//
// The sphere's own parameterisation IS its UV map, which is the point of the
// exercise: u is the angle round the equator, v the angle pole to pole, both
// already normalised to 0..1 by the generation loop.
//
// v is flipped because TextureCache loads images with row 0 at the BOTTOM (to
// match OpenGL), while the generation loop starts at the north pole.
std::vector<glm::vec2> sphere(unsigned latSegments, unsigned lonSegments);

// Planar per-face mapping for a box whose vertices span -0.5 .. 0.5.
//
// Returns one UV per TRIANGLE CORNER -- three per face, in the order the
// corners appear in `faces` -- not one per vertex. This is the part worth
// understanding: a cube has eight corners but twenty-four distinct
// (corner, face) pairs, and each pair wants a different UV, so no per-vertex
// map can exist. Cube::setupCube() already emits one vertex per triangle
// corner, so a per-corner map lines up with what it uploads.
//
// faceNormals is indexed as faceNormals[i / 2]: the cube stores six face
// normals for twelve triangles, two triangles per face.
std::vector<glm::vec2> cube(const std::vector<glm::vec3>& vertices,
                            const std::vector<std::vector<int> >& faces,
                            const std::vector<glm::vec3>& faceNormals);

// Planar per-face projection for ANY triangle mesh: Pyramid, Icosahedron, and
// whatever else has flat faces and no natural parameterisation.
//
// For each face the normal comes from the triangle itself rather than a
// normals array, so this needs nothing but the geometry. The two axes the
// normal is least aligned with become u and v, and positions are normalised by
// the mesh's bounding box so the result lands in 0..1.
//
// Returns one UV per triangle corner.
//
// Seams between faces are inherent, not a defect: projecting a closed solid
// onto planes cannot be continuous. On an icosahedron every one of the 20
// faces gets its own copy of the image.
std::vector<glm::vec2> planarPerFace(const std::vector<glm::vec3>& vertices,
                                     const std::vector<std::vector<int> >& faces);

// Parametric grid mapping, for surfaces generated by a nested (i, j) loop:
// Mobius and Custom, and the same shape of loop Sphere uses.
//
// `uSteps` and `vSteps` are the loop bounds; the generator is assumed to have
// pushed (uSteps + 1) * (vSteps + 1) vertices with j varying fastest, which is
// what all of them do. Returns one UV per UNIQUE vertex -- callers expand it
// per corner alongside their vertex data.
//
// flipV matches the image convention: an image loaded for GL has row 0 at the
// bottom, so a generator that starts at the top of the surface wants it set.
std::vector<glm::vec2> parametricGrid(unsigned uSteps, unsigned vSteps,
                                      bool flipU = false, bool flipV = false);

// Cylindrical projection about the Y axis, one UV per TRIANGLE CORNER.
//
// For meshes shaped roughly like a solid of revolution that arrive with no
// parameterisation to reuse -- the Teapot, whose vertices come out of a table
// of Bezier patches as a plain triangle soup.
//
// Per corner rather than per vertex because of the wrap seam: a triangle
// spanning the back of the mesh has corners at u = 0.98 and u = 0.02, and
// interpolating between them the short way requires giving one of them a u past
// 1.0 -- a different value for the same point in space depending on which
// triangle is asking. See the implementation for what that looks like when it
// is left unrepaired.
std::vector<glm::vec2> cylindricalPerCorner(const std::vector<glm::vec3>& vertices,
                                            const std::vector<std::vector<int> >& faces);

} // namespace TexCoords

#endif // TEXCOORDS_H
